# Generated by Django 4.1.7 on 2023-05-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visitor_alter_portfolio_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
